### ISSUE TITLE
A valid instruction missing from the output.

### ISSUE THREAD

**Issue by ByteWhite1x1** [BeaEngine/beaengine#21]
Hi.

The issue is quite hard to explain so here is a video of the issue: https://gofile.io/?c=WcAWBd

The tool used in the video: https://overlayhack.com/cheat-tool-set

**Comment by BeaEngine** [comment]
hi,
I think the issue occurs because the disasm engine is used in two different ways:

- first, you try to disassemble the instruction flaw from 0x148029090. If so, disasm engine analyzes instructions "on the fly" and pass through instruction located at 0x1480290A0. First instruction is located at 0x9090, next one at 0x9097, next one at 0x909b, next one at 0x909c, next one at 0x909e. This last one is 3 bytes long "00 48 89". So the next instruction is located at 0x90A1, not 0x90A0. 
- Next, you try to disassemble the instruction flaw in the middle of the previous one at 0x1480290A0. According to the previous disasm list, you try to disassemble in the middle of the instruction located at 0x909e. This explains why you have two different disasm lists

Hope it helps

**Comment by BeaEngine** [comment]
here is the output I have with BeaEngine 5:

```
0x00000000 48 8d 2d 61 29 76 05           lea rbp, qword ptr [000055BEA0BF2238h]
0x00000007 48 87 2c 24                    xchg qword ptr [rsp+00h], rbp
0x0000000b c3                             ret 
0x0000000c 31 0f                          xor dword ptr [rdi], ecx
0x0000000e 00 48 89                       add byte ptr [rax-77h], cl
0x00000011 5c                             pop rsp
0x00000012 24 08                          and al, 08h

```

**Comment by ByteWhite1x1** [comment]
Hi. Silly me.

Should've provided the output in first place (I was very tired yesterday). You're right. It's missing because the instruction pointer is getting incremented according to the length of the previous instruction.

The reason the "00000001480290A0 - 48 89 5C 24 08 - mov qword ptr [rsp+08h], rbx Length: 5"
is missing from the list.

[0] 0000000148029090 - 48 8D 2D 61 29 76 05 - lea rbp, qword ptr [000000014D78B9F8h] Length: 7
[1] 0000000148029097 - 48 87 2C 24 - xchg qword ptr [rsp], rbp Length: 4
[2] 000000014802909B - C3 - ret  Length: 1
[3] 000000014802909C - 31 0F - xor dword ptr [rdi], ecx Length: 2
[4] 000000014802909F - 00 48 89 - add byte ptr [rax-77h], cl Length: 3

The next is actually at 0x90A2:

[5] 00000001480290A2 - 5C - pop rsp Length: 1

I encountered this "issue" because there is a logic in my software that attempts to auto-detect the correct function start address based on the entered instruction address. I figured that I must be do some kind of 0x10 alignment fix in order to solve this issue.

Thanks. I think I got it now how to fix it.
